# Generated by Django 3.0 on 2023-04-18 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mirai', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
